import { Button } from "@/components/ui/button"
import {
  Card,
  // CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

import styled from "styled-components"

const AlertCardComponent = styled.div`
padding: 20px;
`;

type ComponentProps = {
    id: number;
    alert_name: string,
    markResolved?: (id: number) => void;
}

export function AlertCard(props: ComponentProps) {

    const { id, alert_name, markResolved } = props;

    const handleSubmit = () => {
        if (!id || !markResolved) {
            return
        }

        markResolved(id);
    }

    return (
    <AlertCardComponent>
        <Card className="w-full max-w-sm">
            <CardHeader>
            <CardTitle>Alert {id}</CardTitle>
            <CardDescription>
                This alert was generated by a {alert_name} event
            </CardDescription>

            </CardHeader>
            <CardContent>
            <form>
                <div className="flex flex-col gap-6">
                <div className="grid gap-2">
                    <Label htmlFor="email">Email</Label>
                    <Input
                    id="email"
                    type="email"
                    placeholder="m@example.com"
                    required
                    />
                </div>
                <div className="grid gap-2">
                    <div className="flex items-center">
                    <Label htmlFor="password">Password</Label>
                    <a
                        href="#"
                        className="ml-auto inline-block text-sm underline-offset-4 hover:underline"
                    >
                        Forgot your password?
                    </a>
                    </div>
                    <Input id="password" type="password" required />
                </div>
                </div>
            </form>
            </CardContent>
            <CardFooter className="flex-col gap-2">
            {markResolved && 
            <Button type="submit" className="w-full" onClick={handleSubmit}>
                Mark Resolved
            </Button>
            }
            

            </CardFooter>
        </Card>
    </AlertCardComponent>
  )

}